#############################################################################
# Makefile for building: animation
# Generated by qmake (2.01a) (Qt 4.6.2) on: Sun Nov 20 22:05:17 2011
# Project:  animation.pro
# Template: subdirs
# Command: /usr/bin/qmake -unix -config release -o Makefile animation.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-engine \
		sub-examples-3-rigidbody \
		sub-examples-4-particlesystem

engine//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) engine/ || $(MKDIR) engine/ 
	cd engine/ && $(QMAKE) /home/seba/src/animation/engine/engine.pro -unix -config release -o $(MAKEFILE)
sub-engine-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) engine/ || $(MKDIR) engine/ 
	cd engine/ && $(QMAKE) /home/seba/src/animation/engine/engine.pro -unix -config release -o $(MAKEFILE)
sub-engine: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE)
sub-engine-make_default-ordered: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) 
sub-engine-make_default: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) 
sub-engine-make_first-ordered: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) first
sub-engine-make_first: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) first
sub-engine-all-ordered: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) all
sub-engine-all: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) all
sub-engine-clean-ordered: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) clean
sub-engine-clean: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) clean
sub-engine-distclean-ordered: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) distclean
sub-engine-distclean: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) distclean
sub-engine-install_subtargets-ordered: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) install
sub-engine-install_subtargets: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) install
sub-engine-uninstall_subtargets-ordered: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-engine-uninstall_subtargets: engine//$(MAKEFILE) FORCE
	cd engine/ && $(MAKE) -f $(MAKEFILE) uninstall
examples/3-rigidbody//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) examples/3-rigidbody/ || $(MKDIR) examples/3-rigidbody/ 
	cd examples/3-rigidbody/ && $(QMAKE) /home/seba/src/animation/examples/3-rigidbody/3-rigidbody.pro -unix -config release -o $(MAKEFILE)
sub-examples-3-rigidbody-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) examples/3-rigidbody/ || $(MKDIR) examples/3-rigidbody/ 
	cd examples/3-rigidbody/ && $(QMAKE) /home/seba/src/animation/examples/3-rigidbody/3-rigidbody.pro -unix -config release -o $(MAKEFILE)
sub-examples-3-rigidbody: examples/3-rigidbody//$(MAKEFILE) FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE)
sub-examples-3-rigidbody-make_default-ordered: examples/3-rigidbody//$(MAKEFILE) sub-engine-make_default-ordered  FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) 
sub-examples-3-rigidbody-make_default: examples/3-rigidbody//$(MAKEFILE) FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) 
sub-examples-3-rigidbody-make_first-ordered: examples/3-rigidbody//$(MAKEFILE) sub-engine-make_first-ordered  FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) first
sub-examples-3-rigidbody-make_first: examples/3-rigidbody//$(MAKEFILE) FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) first
sub-examples-3-rigidbody-all-ordered: examples/3-rigidbody//$(MAKEFILE) sub-engine-all-ordered  FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) all
sub-examples-3-rigidbody-all: examples/3-rigidbody//$(MAKEFILE) FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) all
sub-examples-3-rigidbody-clean-ordered: examples/3-rigidbody//$(MAKEFILE) sub-engine-clean-ordered  FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) clean
sub-examples-3-rigidbody-clean: examples/3-rigidbody//$(MAKEFILE) FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) clean
sub-examples-3-rigidbody-distclean-ordered: examples/3-rigidbody//$(MAKEFILE) sub-engine-distclean-ordered  FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) distclean
sub-examples-3-rigidbody-distclean: examples/3-rigidbody//$(MAKEFILE) FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) distclean
sub-examples-3-rigidbody-install_subtargets-ordered: examples/3-rigidbody//$(MAKEFILE) sub-engine-install_subtargets-ordered  FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) install
sub-examples-3-rigidbody-install_subtargets: examples/3-rigidbody//$(MAKEFILE) FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) install
sub-examples-3-rigidbody-uninstall_subtargets-ordered: examples/3-rigidbody//$(MAKEFILE) sub-engine-uninstall_subtargets-ordered  FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-examples-3-rigidbody-uninstall_subtargets: examples/3-rigidbody//$(MAKEFILE) FORCE
	cd examples/3-rigidbody/ && $(MAKE) -f $(MAKEFILE) uninstall
examples/4-particlesystem//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) examples/4-particlesystem/ || $(MKDIR) examples/4-particlesystem/ 
	cd examples/4-particlesystem/ && $(QMAKE) /home/seba/src/animation/examples/4-particlesystem/4-particlesystem.pro -unix -config release -o $(MAKEFILE)
sub-examples-4-particlesystem-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) examples/4-particlesystem/ || $(MKDIR) examples/4-particlesystem/ 
	cd examples/4-particlesystem/ && $(QMAKE) /home/seba/src/animation/examples/4-particlesystem/4-particlesystem.pro -unix -config release -o $(MAKEFILE)
sub-examples-4-particlesystem: examples/4-particlesystem//$(MAKEFILE) FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE)
sub-examples-4-particlesystem-make_default-ordered: examples/4-particlesystem//$(MAKEFILE) sub-examples-3-rigidbody-make_default-ordered  FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) 
sub-examples-4-particlesystem-make_default: examples/4-particlesystem//$(MAKEFILE) FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) 
sub-examples-4-particlesystem-make_first-ordered: examples/4-particlesystem//$(MAKEFILE) sub-examples-3-rigidbody-make_first-ordered  FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) first
sub-examples-4-particlesystem-make_first: examples/4-particlesystem//$(MAKEFILE) FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) first
sub-examples-4-particlesystem-all-ordered: examples/4-particlesystem//$(MAKEFILE) sub-examples-3-rigidbody-all-ordered  FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) all
sub-examples-4-particlesystem-all: examples/4-particlesystem//$(MAKEFILE) FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) all
sub-examples-4-particlesystem-clean-ordered: examples/4-particlesystem//$(MAKEFILE) sub-examples-3-rigidbody-clean-ordered  FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) clean
sub-examples-4-particlesystem-clean: examples/4-particlesystem//$(MAKEFILE) FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) clean
sub-examples-4-particlesystem-distclean-ordered: examples/4-particlesystem//$(MAKEFILE) sub-examples-3-rigidbody-distclean-ordered  FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) distclean
sub-examples-4-particlesystem-distclean: examples/4-particlesystem//$(MAKEFILE) FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) distclean
sub-examples-4-particlesystem-install_subtargets-ordered: examples/4-particlesystem//$(MAKEFILE) sub-examples-3-rigidbody-install_subtargets-ordered  FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) install
sub-examples-4-particlesystem-install_subtargets: examples/4-particlesystem//$(MAKEFILE) FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) install
sub-examples-4-particlesystem-uninstall_subtargets-ordered: examples/4-particlesystem//$(MAKEFILE) sub-examples-3-rigidbody-uninstall_subtargets-ordered  FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-examples-4-particlesystem-uninstall_subtargets: examples/4-particlesystem//$(MAKEFILE) FORCE
	cd examples/4-particlesystem/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: animation.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -config release -o Makefile animation.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -config release -o Makefile animation.pro

qmake_all: sub-engine-qmake_all sub-examples-3-rigidbody-qmake_all sub-examples-4-particlesystem-qmake_all FORCE

make_default: sub-engine-make_default-ordered sub-examples-3-rigidbody-make_default-ordered sub-examples-4-particlesystem-make_default-ordered FORCE
make_first: sub-engine-make_first-ordered sub-examples-3-rigidbody-make_first-ordered sub-examples-4-particlesystem-make_first-ordered FORCE
all: sub-engine-all-ordered sub-examples-3-rigidbody-all-ordered sub-examples-4-particlesystem-all-ordered FORCE
clean: sub-engine-clean-ordered sub-examples-3-rigidbody-clean-ordered sub-examples-4-particlesystem-clean-ordered FORCE
distclean: sub-engine-distclean-ordered sub-examples-3-rigidbody-distclean-ordered sub-examples-4-particlesystem-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-engine-install_subtargets-ordered sub-examples-3-rigidbody-install_subtargets-ordered sub-examples-4-particlesystem-install_subtargets-ordered FORCE
uninstall_subtargets: sub-engine-uninstall_subtargets-ordered sub-examples-3-rigidbody-uninstall_subtargets-ordered sub-examples-4-particlesystem-uninstall_subtargets-ordered FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

