######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 20 21:33:52 2011
######################################################################
include(../../engine/engine.pri)

LIBS += -L../../engine/lib
LIBS += -lGLEW -lglut -lengine
OBJECTS_DIR = obj
TEMPLATE = app
TARGET = 2-ik
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/MainApplication.h
SOURCES += src/Main.cpp src/MainApplication.cpp
