#!/bin/bash

PRO=${PWD##*/}.pro

qmake -project -t app -r -o $PRO \
"LIBS += -L../../engine/lib" \
"LIBS += -lGL -lGLU -lGLEW -lglut -lengine" \
"OBJECTS_DIR = obj"

sed -i '4i include(../../engine/engine.pri)' $PRO

