######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 18 15:19:15 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include src
INCLUDEPATH += . include

# Input
HEADERS += include/MainApplication.h
SOURCES += src/Main.cpp src/MainApplication.cpp
LIBS += -lGL -lGLU -lGLEW -lglut -L../common/lib -lcommon
OBJECTS_DIR = obj
INCLUDEPATH += ../common/include
